## Lotteria Pandas

In [2]:
import numpy as np

numeri = np.arange(1, 91)
numeri

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90])

In [3]:
#mescolo le palline
np.random.shuffle(numeri)
numeri

array([82, 33, 49, 80, 39, 61, 83, 66, 26, 67, 78, 47, 22, 87, 77,  2, 52,
       30, 46, 12, 28,  4, 40,  3, 65, 38, 81, 51, 71, 57,  5, 63, 79, 15,
       29, 64, 90, 55, 84, 27, 70, 56, 16, 48, 17, 14, 10, 74, 60, 31, 11,
       53, 45, 72, 21,  1, 43, 42, 32, 20, 68, 25, 13, 54, 19, 86, 73, 50,
       41, 18, 34, 89, 75, 23,  6, 88, 69, 62,  9, 37, 36,  7, 85, 44, 35,
       24, 58,  8, 59, 76])

In [29]:
#creo una lista numpy vuota in cui inseriro le estrazioni

estrazioni = np.array([])

In [30]:
for i in range(20):
    #rimescolo i numeri
    np.random.shuffle(numeri)

    #estraggo 5 numeri
    estratti = numeri[0:5]
    #print(estratti)

    #li aggiungo alla lista di estrazioni
    estrazioni = np.append(estrazioni, [estratti])

estrazioni = estrazioni.reshape(20, 5)
estrazioni

array([[88.,  7.,  5., 30., 73.],
       [55., 10., 59., 28., 88.],
       [68., 54., 26., 47., 57.],
       [25., 29.,  4., 16., 32.],
       [83., 30., 56., 57., 81.],
       [63., 71., 74., 58., 65.],
       [50., 44., 90., 66.,  2.],
       [ 1., 17., 83., 66., 34.],
       [48., 24., 10.,  6., 67.],
       [66., 85., 32., 45., 81.],
       [35., 67., 85., 50., 73.],
       [45., 76., 36., 43., 25.],
       [17., 15., 16., 50., 35.],
       [33., 53., 75., 42., 55.],
       [47., 56., 69., 46., 81.],
       [34., 55., 52., 69., 49.],
       [79., 56., 32., 20., 42.],
       [36., 12., 71.,  4., 25.],
       [48., 32., 38., 47., 19.],
       [85., 54., 25.,  4., 13.]])

In [31]:
import pandas as pd

#creo un intervallo di date con pandas
dates = pd.date_range('20260101', periods=20)
dates

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
               '2026-01-09', '2026-01-10', '2026-01-11', '2026-01-12',
               '2026-01-13', '2026-01-14', '2026-01-15', '2026-01-16',
               '2026-01-17', '2026-01-18', '2026-01-19', '2026-01-20'],
              dtype='datetime64[ns]', freq='D')

In [32]:
df = pd.DataFrame(data=estrazioni, index=dates)
df

,0,1,2,3,4
2026-01-01,88.0,7.0,5.0,30.0,73.0
2026-01-02,55.0,10.0,59.0,28.0,88.0
2026-01-03,68.0,54.0,26.0,47.0,57.0
2026-01-04,25.0,29.0,4.0,16.0,32.0
2026-01-05,83.0,30.0,56.0,57.0,81.0
2026-01-06,63.0,71.0,74.0,58.0,65.0
2026-01-07,50.0,44.0,90.0,66.0,2.0
2026-01-08,1.0,17.0,83.0,66.0,34.0
2026-01-09,48.0,24.0,10.0,6.0,67.0
2026-01-10,66.0,85.0,32.0,45.0,81.0


In [15]:
for i in range(len(df)):
    print(df.iloc[i])

0    42.0
1    83.0
2    57.0
3    64.0
4    14.0
Name: 2026-01-01 00:00:00, dtype: float64
0     6.0
1    36.0
2    12.0
3    41.0
4    72.0
Name: 2026-01-02 00:00:00, dtype: float64
0    21.0
1    85.0
2    38.0
3    14.0
4    16.0
Name: 2026-01-03 00:00:00, dtype: float64
0    27.0
1    68.0
2    35.0
3     6.0
4    58.0
Name: 2026-01-04 00:00:00, dtype: float64
0     3.0
1    60.0
2    74.0
3    86.0
4    25.0
Name: 2026-01-05 00:00:00, dtype: float64


In [33]:
ritardatari = {}
for i in range(len(df)):
    riga = df.iloc[i]
    for num in riga:
        gg = len(df)-i
        #print(num, gg)
        ritardatari[num] = gg

ritardatari


{88.0: 19,
 7.0: 20,
 5.0: 20,
 30.0: 16,
 73.0: 10,
 55.0: 5,
 10.0: 12,
 59.0: 19,
 28.0: 19,
 68.0: 18,
 54.0: 1,
 26.0: 18,
 47.0: 2,
 57.0: 16,
 25.0: 1,
 29.0: 17,
 4.0: 1,
 16.0: 8,
 32.0: 2,
 83.0: 13,
 56.0: 4,
 81.0: 6,
 63.0: 15,
 71.0: 3,
 74.0: 15,
 58.0: 15,
 65.0: 15,
 50.0: 8,
 44.0: 14,
 90.0: 14,
 66.0: 11,
 2.0: 14,
 1.0: 13,
 17.0: 8,
 34.0: 5,
 48.0: 2,
 24.0: 12,
 6.0: 12,
 67.0: 10,
 85.0: 1,
 45.0: 9,
 35.0: 8,
 76.0: 9,
 36.0: 3,
 43.0: 9,
 15.0: 8,
 33.0: 7,
 53.0: 7,
 75.0: 7,
 42.0: 4,
 69.0: 5,
 46.0: 6,
 52.0: 5,
 49.0: 5,
 79.0: 4,
 20.0: 4,
 12.0: 3,
 38.0: 2,
 19.0: 2,
 13.0: 1}

In [38]:
df = pd.DataFrame(list(ritardatari.items()), columns=['Valore', 'Conteggio'])
df.head()

,Valore,Conteggio
0,88.0,19
1,7.0,20
2,5.0,20
3,30.0,16
4,73.0,10


In [36]:
df = df.sort_values(by="Conteggio", ascending=False)
df.head(10)

,Valore,Conteggio
2,5.0,20
1,7.0,20
0,88.0,19
7,59.0,19
8,28.0,19
9,68.0,18
11,26.0,18
15,29.0,17
13,57.0,16
3,30.0,16


In [37]:
df.describe()

,Valore,Conteggio
count,60.000000,60.000000
mean,44.133333,9.033333
std,25.064301,5.877180
min,1.000000,1.000000
25%,24.750000,4.000000
50%,45.500000,8.000000
75%,65.250000,14.000000
max,90.000000,20.000000
