### Lotteria Pandas

Simulo delle estrazioni del Lotto. 
Voglio trovare i numeri ritardatari.

In [2]:
import numpy as np

numeri = np.arange(1, 91)
numeri

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90])

In [6]:
#mescolo le palline
np.random.shuffle(numeri)
numeri

array([71, 42, 54,  6, 30, 74, 50, 22, 79, 81,  5, 65, 55, 63, 24, 18, 13,
       23, 87, 29, 33, 83, 51, 77, 40, 10, 36, 46, 56, 27, 57, 32, 61, 68,
       45,  2, 48, 52, 88, 26, 53, 59, 72, 14, 19, 21, 78, 31, 76, 47, 73,
       12, 17, 80, 62, 11, 67, 64,  9,  4, 90, 84, 49, 58,  8, 20, 16,  1,
       85, 82,  7, 37, 70, 44, 34, 25, 43, 86, 28, 89, 38, 39, 15, 41, 66,
       60, 69,  3, 75, 35])

In [8]:
#creo una lista in cui mettere le estrazioni
estrazioni = np.array([])

In [9]:
for i in range(20):
    #rimescolo
    np.random.shuffle(numeri)
    #prendo i primi 5
    estratti = numeri[:5]
    print(estratti)

    #aggiungo a estrazioni
    estrazioni = np.append(estrazioni, [estratti])
    
estrazioni

[70 44 18 37 15]
[55 88 41  7 58]
[44 12 87  4 30]
[72 38 80 30 36]
[55 63  4 30  6]
[14 36 42 12 34]
[ 9  4  3 72  1]
[47 80 84 73 18]
[74 42 25 61  9]
[ 5 37 58 41 28]
[53 44 72  3 77]
[85 40 56 26 12]
[60 73  2 38 55]
[21 53 22 42 89]
[30 37 49 57 75]
[42 62 48 25 22]
[87 55 63 85 37]
[11 51  7 81 18]
[77 78 66 56 50]
[13  7  9 17 31]


array([70., 44., 18., 37., 15., 55., 88., 41.,  7., 58., 44., 12., 87.,
        4., 30., 72., 38., 80., 30., 36., 55., 63.,  4., 30.,  6., 14.,
       36., 42., 12., 34.,  9.,  4.,  3., 72.,  1., 47., 80., 84., 73.,
       18., 74., 42., 25., 61.,  9.,  5., 37., 58., 41., 28., 53., 44.,
       72.,  3., 77., 85., 40., 56., 26., 12., 60., 73.,  2., 38., 55.,
       21., 53., 22., 42., 89., 30., 37., 49., 57., 75., 42., 62., 48.,
       25., 22., 87., 55., 63., 85., 37., 11., 51.,  7., 81., 18., 77.,
       78., 66., 56., 50., 13.,  7.,  9., 17., 31.])

In [10]:
#riarrangio i dati
estrazioni = estrazioni.reshape(20, 5)
estrazioni

array([[70., 44., 18., 37., 15.],
       [55., 88., 41.,  7., 58.],
       [44., 12., 87.,  4., 30.],
       [72., 38., 80., 30., 36.],
       [55., 63.,  4., 30.,  6.],
       [14., 36., 42., 12., 34.],
       [ 9.,  4.,  3., 72.,  1.],
       [47., 80., 84., 73., 18.],
       [74., 42., 25., 61.,  9.],
       [ 5., 37., 58., 41., 28.],
       [53., 44., 72.,  3., 77.],
       [85., 40., 56., 26., 12.],
       [60., 73.,  2., 38., 55.],
       [21., 53., 22., 42., 89.],
       [30., 37., 49., 57., 75.],
       [42., 62., 48., 25., 22.],
       [87., 55., 63., 85., 37.],
       [11., 51.,  7., 81., 18.],
       [77., 78., 66., 56., 50.],
       [13.,  7.,  9., 17., 31.]])

In [11]:
import pandas as pd

dates = pd.date_range("20260101", periods=20)
dates

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
               '2026-01-09', '2026-01-10', '2026-01-11', '2026-01-12',
               '2026-01-13', '2026-01-14', '2026-01-15', '2026-01-16',
               '2026-01-17', '2026-01-18', '2026-01-19', '2026-01-20'],
              dtype='datetime64[ns]', freq='D')

In [12]:
df = pd.DataFrame(data=estrazioni, index=dates)
df

,0,1,2,3,4
2026-01-01,70.0,44.0,18.0,37.0,15.0
2026-01-02,55.0,88.0,41.0,7.0,58.0
2026-01-03,44.0,12.0,87.0,4.0,30.0
2026-01-04,72.0,38.0,80.0,30.0,36.0
2026-01-05,55.0,63.0,4.0,30.0,6.0
2026-01-06,14.0,36.0,42.0,12.0,34.0
2026-01-07,9.0,4.0,3.0,72.0,1.0
2026-01-08,47.0,80.0,84.0,73.0,18.0
2026-01-09,74.0,42.0,25.0,61.0,9.0
2026-01-10,5.0,37.0,58.0,41.0,28.0


In [15]:
ritardatari = {}
for i in range(len(df)):
    riga = df.iloc[i]
    for num in riga:
        gg = len(df)-i
        ritardatari[num] = gg
ritardatari
    

{70.0: 20,
 44.0: 10,
 18.0: 3,
 37.0: 4,
 15.0: 20,
 55.0: 4,
 88.0: 19,
 41.0: 11,
 7.0: 1,
 58.0: 11,
 12.0: 9,
 87.0: 4,
 4.0: 14,
 30.0: 6,
 72.0: 10,
 38.0: 8,
 80.0: 13,
 36.0: 15,
 63.0: 4,
 6.0: 16,
 14.0: 15,
 42.0: 5,
 34.0: 15,
 9.0: 1,
 3.0: 10,
 1.0: 14,
 47.0: 13,
 84.0: 13,
 73.0: 8,
 74.0: 12,
 25.0: 5,
 61.0: 12,
 5.0: 11,
 28.0: 11,
 53.0: 7,
 77.0: 2,
 85.0: 4,
 40.0: 9,
 56.0: 2,
 26.0: 9,
 60.0: 8,
 2.0: 8,
 21.0: 7,
 22.0: 5,
 89.0: 7,
 49.0: 6,
 57.0: 6,
 75.0: 6,
 62.0: 5,
 48.0: 5,
 11.0: 3,
 51.0: 3,
 81.0: 3,
 78.0: 2,
 66.0: 2,
 50.0: 2,
 13.0: 1,
 17.0: 1,
 31.0: 1}

In [18]:
df = pd.DataFrame(list(ritardatari.items()), columns=['numero', "ritardo"])
df.head(4)

,numero,ritardo
0,70.0,20
1,44.0,10
2,18.0,3
3,37.0,4


In [19]:
df = df.sort_values(by="ritardo", ascending=False)
df.head(5)

,numero,ritardo
0,70.0,20
4,15.0,20
6,88.0,19
19,6.0,16
22,34.0,15


In [20]:
df.describe()

,numero,ritardo
count,59.000000,59.000000
mean,43.745763,7.813559
std,26.906347,5.114127
min,1.000000,1.000000
25%,19.500000,4.000000
50%,44.000000,7.000000
75%,64.500000,11.000000
max,89.000000,20.000000
