## NumPy

In [1]:
# %pip install numpy

In [2]:
import numpy as np

Numpy gestisce liste di numeri che sono definite **array**

In [3]:
v1 = np.array([1,2,3,4,5,6,7,8,9])
print(v1)

[1 2 3 4 5 6 7 8 9]


In [4]:
#tabella a 2 dimensioni -> matrice
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
v1.shape

(9,)

In [6]:
m1.shape

(3, 3)

In [7]:
#creo una lista di valori e la trasformo in tabella
v2 = np.array([1,2,3,4,5,6,7,8,9])
print(v2)
print(v2.shape)
v2.shape = (3,3)
print(v2)

[1 2 3 4 5 6 7 8 9]
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Accesso ai valori

In [8]:
v1[0] = 99
print(v1)
print(v1[2])

[99  2  3  4  5  6  7  8  9]
3


In [9]:
v2[0,0] = 88
print(v2)

[[88  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [10]:
n = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12])
print("3° elemento:", n[2])
print("ultimo: ", n[-1])
print("range: ", n[3:6])
print("da 7 a fine", n[7:])
print("da inizio a 7", n[:7])

3° elemento: 2
ultimo:  12
range:  [3 4 5]
da 7 a fine [ 7  8  9 10 11 12]
da inizio a 7 [0 1 2 3 4 5 6]


In [11]:
n = np.array([1,2,3,4,5,6,7,8,9])
n2 = n.reshape(3,3)
print(n2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
#estraggo una riga dalla tabella/matrice
print(n2[1])

[4 5 6]


In [13]:
#estraggo una colonna dalla matrice
print(n2[:,2])

[3 6 9]


In [14]:
#sottomatrice
print( n2[ 1:3, 1:3 ] )

[[5 6]
 [8 9]]


### Modifiche all'array

In [15]:
#aggiungo elementi
n = np.array([1,2,3,4,5,6,7,8,9])
n2 = np.append(n, 100)
print(n2)
n3 = np.insert(n, 3, 100)
print(n3)

[  1   2   3   4   5   6   7   8   9 100]
[  1   2   3 100   4   5   6   7   8   9]


Tutti gli elementi di un array sono omogenei

In [16]:
print(n.dtype)

int32


In [17]:
f = np.array([1.2, 2.3, 3.4, 4.5])
print(f.dtype)

float64


In [18]:
n = np.array([1,2,3])
print(n)
print(n.dtype)
n = np.append(n, 12.3)
print(n)
print(n.dtype)

[1 2 3]
int32
[ 1.   2.   3.  12.3]
float64


In [19]:
n = np.array([1,2,3,4])
f = np.array(n, dtype=float)
print(f, f.dtype)

[1. 2. 3. 4.] float64


In [20]:
print(n)
n2 = n.astype(np.float16)
print(n2, n2.dtype)

[1 2 3 4]
[1. 2. 3. 4.] float16


In [21]:
#numeri complessi
c1 = np.array([1+2j, 2+3j])
print(c1, c1.dtype)

[1.+2.j 2.+3.j] complex128


## Operazioni con array

In [22]:
a = np.array([10,20,30,40,50])
b = np.array([11,22,34,45,67])

print(a+b)
print(a-b)
print(a*b)

[ 21  42  64  85 117]
[ -1  -2  -4  -5 -17]
[ 110  440 1020 1800 3350]


In [23]:
print(a*1.22)

[12.2 24.4 36.6 48.8 61. ]


In [24]:
print( a > 25)

[False False  True  True  True]


In [25]:
#b = b * 2
b *= 2 
print(b)

b += 1
print(b)

[ 22  44  68  90 134]
[ 23  45  69  91 135]


## Generare numeri

In [26]:
#genero una sequenza, un intervallo
n = np.arange(1, 49)
print(n, len(n), n.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48] 48 (48,)


In [27]:
t1 = np.arange(1,49).reshape(6,8)
print(t1)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]]


In [28]:
t2 = np.arange(1,49).reshape(12,4)
print(t2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]
 [37 38 39 40]
 [41 42 43 44]
 [45 46 47 48]]


In [29]:
#numeri casuali tra 0 e 1
m = np.random.random( (4,4) )
print(m)

[[0.55183574 0.91983776 0.54670946 0.24632552]
 [0.073331   0.1144729  0.92160876 0.31190573]
 [0.36278789 0.74836404 0.63887382 0.69240881]
 [0.37903868 0.95729269 0.23593628 0.47049155]]


In [30]:
#tra 0 e 100
m2 = m*100
print(m2)

[[55.18357378 91.98377551 54.67094572 24.63255234]
 [ 7.33310004 11.44728987 92.16087612 31.19057334]
 [36.27878898 74.83640394 63.88738176 69.24088052]
 [37.90386752 95.72926885 23.59362779 47.04915543]]


In [31]:
m3 = np.random.randint(0, 100, (4,4))
print(m3)

[[ 6 30 89 68]
 [77 30 10 31]
 [65 96 68 72]
 [74 28 97 69]]


In [32]:
m4 = np.empty((3,4))
print(m4)

[[9.58693973e-312 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [1.08221785e-312 2.46567317e+179 5.20765788e-090 1.69175722e-052]
 [5.41400911e-067 2.37776350e+184 3.99910963e+252 1.20009786e-071]]


In [33]:
m4 = np.zeros((3,3))
print(m4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
m5 = np.ones((2,2))
print(m5)

[[1. 1.]
 [1. 1.]]


In [35]:
m6 = np.full((2,2), 7)
print(m6)
m6 = np.full((2,2), True)
print(m6)
m6 = np.full((2,2), 'a')
print(m6)

[[7 7]
 [7 7]]
[[ True  True]
 [ True  True]]
[['a' 'a']
 ['a' 'a']]


In [36]:
m7 = np.linspace(10, 100, num=5)
print(m7)

[ 10.   32.5  55.   77.5 100. ]


# esempio lotto
estrarre 5 numeri casuali e diversi tra di loro da una lista (estrazione del lotto)

In [37]:
# sembra ok ma non va bene
e1 = np.random.randint(1,90, 5)
print(e1)
# è come estrarre le palline e poi rimetterle nel sacchetto (posso avere duplicati)

#creo le mie 90 palline
elenco_numeri = np.arange(1,91)
print(elenco_numeri)
#mischio il sacchetto
np.random.shuffle(elenco_numeri)
print(elenco_numeri)
#estraggo i primi 5 numeri
estrazione = elenco_numeri[:5]
print(estrazione)


[63  8 51 51 54]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90]
[20 84 15 35  8 64 54  2 65  1 38 57 62 19 46  7 43 87 58 61 90 27 41 26
 34 51 40 55 56 14 42 24 72 81 80 75  4 89 29 76 68 28 32 39 37 67 59 70
 33 88 10 85 50 48 16 66  3 77 74 17 45 63  6 18 21 60 73 30  9 78 47 13
 22 11 49 82 53 52  5 79 83 36 69 44 25 12 31 71 23 86]
[20 84 15 35  8]


## Filtraggio numeri

In [38]:
n = np.random.randint(0,100, 20)
print(n)

#filtro n ed estraggo i numeri minori di 50
nf = n[ n<50 ]
print(nf)

[ 0 39 26 64  0  0 84  6 38 22 62 73 97 60 36 31 54  5 72 97]
[ 0 39 26  0  0  6 38 22 36 31  5]


In [39]:
#filtro n e estraggo solo lgi elementi che valgono 2
nf = n[ n==2 ] 
print(nf)

[]


In [40]:
#filtro n ed estraggo i numeri diversi da 2 (diverso è !=)
nf = n[ n!=2 ]
print(nf)

[ 0 39 26 64  0  0 84  6 38 22 62 73 97 60 36 31 54  5 72 97]


In [41]:
#stampo solo i numeri pari
npa = n[ (n%2) == 0 ]
print(npa)

[ 0 26 64  0  0 84  6 38 22 62 60 36 54 72]


In [42]:
#numeri compresi in un intervallo 
#combino due espressioni che devono essere vere entrambe -> AND -> &
#numeri tra 20 e 30
nf = n[ (n>=20) & (n<=30) ]
print(nf)


[26 22]


In [43]:
#numeri esterni a un intervallo
#numeri maggiori di 40 o numeri minori di 20
# OR -> |
nf = n[ (n<20) | (n>40) ]
print(nf)

[ 0 64  0  0 84  6 62 73 97 60 54  5 72 97]


## Where

In [45]:
n = np.random.randint(0,100, 20)
print(n)
# where applica l'espressione n>40 agli elementi della lista. Se è vera restituisce n altrimenti 0
nn = np.where( n>40, n, 0 )
print(nn)

[62 52 69 87 32  7 81 36 92 67 95 20 44 19 65 54 55 59 38 39]
[62 52 69 87  0  0 81  0 92 67 95  0 44  0 65 54 55 59  0  0]


In [49]:
n2 = np.where( (n%2 == 0), 'p', 'd' )
print(n)
print(n2)
print(np.where( (n%2 == 0)))


[62 52 69 87 32  7 81 36 92 67 95 20 44 19 65 54 55 59 38 39]
['p' 'p' 'd' 'd' 'p' 'd' 'd' 'p' 'p' 'd' 'd' 'p' 'p' 'd' 'd' 'p' 'd' 'd'
 'p' 'd']
(array([ 0,  1,  4,  7,  8, 11, 12, 15, 18], dtype=int64),)


## Arrotondamenti

In [50]:
#genero 10 numeri casuali tra 0 e 1
v = np.random.random(10)
print(v)

[0.02621658 0.90243655 0.92767679 0.50809286 0.56321439 0.64654715
 0.35072223 0.51118202 0.5647816  0.59396873]


In [51]:
#li voglio trasformare in numeri tra 0 e 10
v *= 10.0
print(v)

[0.26216582 9.02436548 9.27676792 5.08092855 5.63214394 6.4654715
 3.5072223  5.11182023 5.64781602 5.93968734]


In [52]:
#elimino un po' di decimali
q = np.around(v, 2)
print(q)

[0.26 9.02 9.28 5.08 5.63 6.47 3.51 5.11 5.65 5.94]


In [53]:
#arrotondo all'intero "superiore"
w = np.ceil(q)
print(w)

[ 1. 10. 10.  6.  6.  7.  4.  6.  6.  6.]


In [54]:
#arrotondo all'intero inferiore
e = np.floor(q)
print(e)

[0. 9. 9. 5. 5. 6. 3. 5. 5. 5.]


## statistiche

In [57]:
n = np.random.randint(2,11, 20)
print(n)

[10  6 10  9  5  6  9  9 10  8  8  4  6  5  8  4  6  2  3  4]


In [59]:
#valore minimo
print(n.min())
print(np.amin(n))

2
2


In [60]:
#valore massimo
print(n.max())
print(np.amax(n))

10
10


In [61]:
#la media
print(np.average(n))

6.6


In [62]:
print("mediana", np.median(n))

mediana 6.0


In [63]:
#somma dei valori di un array
print("somma valori", np.sum(n))

somma valori 132


In [65]:
#somma cumulativa
print(n)
print(np.cumsum(n))

[10  6 10  9  5  6  9  9 10  8  8  4  6  5  8  4  6  2  3  4]
[ 10  16  26  35  40  46  55  64  74  82  90  94 100 105 113 117 123 125
 128 132]


## Files

In [66]:
#carico i valori da un file esterno
n = np.genfromtxt("numeri.txt")
print(n)

[12.3 23.4 34.5 56.7 78.7 88.8 99.9]


In [67]:
#modifico i valori (li incremento del 10%)
n *= 1.10
print(n)

[ 13.53  25.74  37.95  62.37  86.57  97.68 109.89]


In [68]:
#arrotondo così da avere un solo decimale
n2 = np.around(n, 1)
print(n2)

[ 13.5  25.7  38.   62.4  86.6  97.7 109.9]


In [71]:
#salvo i numeri in un formato testo
np.savetxt("numeri_mod.txt", n2, fmt="%0.1f")

In [72]:
#salvataggio in binario
np.save("dati", n2)

In [73]:
#leggo un file di dati binario
n3 = np.load("dati.npy")
print(n3)

[ 13.5  25.7  38.   62.4  86.6  97.7 109.9]


## Esempi

Mi danno una serie di misure (la simuleremo) e di queste fornisco degli indicatori statistici

In [80]:
import numpy as np

#genero i dati delle misure (pesi?)
dati = np.random.random(20) * 100
#riduco i decimali
dati = np.around(dati, 2)
print(dati)

#calcolo gli indici statistici
media = np.average(dati)
dev_std = np.std(dati)
minimo = np.amin(dati)
massimo = np.amax(dati)
mediana = np.median(dati)

print(f"media: {round(media, 2)}\t std: {round(dev_std, 2)}\t min: {minimo}\n max: {massimo}\t mediana: {mediana}")

[70.49 13.82 96.43 30.42 26.52 83.24  6.98  1.5  35.46 35.93 14.08 99.76
 42.86 51.15 34.14 71.75  4.53  9.25 74.5  78.75]
media: 44.08	 std: 31.25	 min: 1.5
 max: 99.76	 mediana: 35.695


Es. 2 - pulizia dati

In [87]:
dati = np.random.randint(0, 30, 40)
#sporco i dati
dati[3] = 999
dati[10] = 999
dati[34] = -1
dati[24] = -1

#filtro i dati fuori range
df = dati[ (dati<100) & (dati >= 0)]
print(df)


[ 2 28  5  3 12  5  9  9 18 12 17 27  3 18  6  8 27  6 12 24  7 24 10 22
  7  8 28 27  6 17 18  6 18  9 22 23]
