## NumPy
Tipo Matlab per Python
Elaborazione di dati in liste e matrici

In [1]:
import numpy as np

creo strutture dati: liste o matrici

In [2]:
v1 = np.array([1,2,3,4,5,6,7,9,0])
v1

array([1, 2, 3, 4, 5, 6, 7, 9, 0])

In [3]:
v1.shape

(9,)

In [4]:
v2 = v1.reshape(3,3)
v2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 9, 0]])

In [8]:
n = v1[0]
print(n)

1


In [9]:
v1.dtype

dtype('int64')

In [11]:
v1[1:4]

array([2, 3, 4])

operazioni

In [19]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

print("a+b", a+b)
print("a-b", a-b)
print("a*b", a*b)
print("a*0.5", a*0.5)
print("a+1", a+1)

print("selezione:", a>25, b>3)



a+b [11 22 33 44]
a-b [ 9 18 27 36]
a*b [ 10  40  90 160]
a*0.5 [ 5. 10. 15. 20.]
a+1 [11 21 31 41]
selezione: [False False  True  True] [False False False  True]


Generare dati

In [21]:
c = np.arange(1,10)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
d = np.arange(1,17).reshape(4,4)
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [23]:
e = np.random.random((4,4))
e

array([[0.36321629, 0.22765378, 0.31497444, 0.20711073],
       [0.19069713, 0.82516098, 0.53621816, 0.97394029],
       [0.28525481, 0.07510272, 0.05908339, 0.75880769],
       [0.41584133, 0.736044  , 0.35933168, 0.251986  ]])

In [24]:
e2 = e*100
e2

array([[36.32162948, 22.76537817, 31.4974443 , 20.71107268],
       [19.06971318, 82.51609816, 53.62181587, 97.39402906],
       [28.5254809 ,  7.51027229,  5.90833931, 75.88076897],
       [41.58413277, 73.60440049, 35.93316781, 25.19859984]])

In [25]:
f = np.random.randint(0,100,(4,4))
f

array([[28, 62, 21, 87],
       [94, 28, 66, 29],
       [42, 28,  4, 93],
       [64, 90, 82, 81]])

In [26]:
g = np.empty((2,2))
g

array([[5.43e-323, 1.04e-322],
       [1.53e-322, 2.03e-322]])

In [27]:
h = np.zeros((3,3))
h

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
h1 = np.full((3,3), 1)
h1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [29]:
n1 = np.arange(0,10)
print(n1)
np.random.shuffle(n1)
print(n1)

[0 1 2 3 4 5 6 7 8 9]
[6 1 9 3 4 8 7 0 5 2]


estrazione del lotto

In [38]:
n1 = np.arange(1, 91)
print(n1)
np.random.shuffle(n1)
estrazione = n1[:6]
print(estrazione)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90]
[20 13 71 48 55 16]


filtri

In [40]:
n1 = np.random.randint(0,100, 20)
print(n1)
nf = n1[n1 < 50]
print(nf)


[30 90 89 52 76 88  6 95 45 92 78  1 60 33 36  6 59  2  8 57]
[30  6 45  1 33 36  6  2  8]


In [41]:
#i numeri pari
pari = n1[n1%2 == 0]
pari

array([30, 90, 52, 76, 88,  6, 92, 78, 60, 36,  6,  2,  8])

In [42]:
#numeri in un intervallo
x = n1[ (n1>30) & (n1<50) ] #numeri di n1 che sono > di 30 E minori di 50
x

array([45, 33, 36])

In [43]:
#numeri in un intervallo
x = n1[ (n1<30) | (n1>50) ] #numeri di n1 che sono < di 30 O > di 50
x

array([90, 89, 52, 76, 88,  6, 95, 92, 78,  1, 60,  6, 59,  2,  8, 57])

In [45]:
x = np.where( (n1%2 == 0), "P", "D" )
x

array(['P', 'P', 'D', 'P', 'P', 'P', 'P', 'D', 'D', 'P', 'P', 'D', 'P',
       'D', 'P', 'P', 'D', 'P', 'P', 'D'], dtype='<U1')

# Files

In [46]:
lista = np.genfromtxt("numeri.txt")
print(lista)

[12.3 23.4 34.5 45.6 56.7 67.8 78.9 98.7 87.6 65.4 54.3 43.3 32.1 11.
  9.5]


In [47]:
lista.dtype

dtype('float64')

In [48]:
lista.size

15

In [49]:
print("min", np.amin(lista))
print("max", np.amax(lista))
print("media", np.average(lista))
print("dev std", np.std(lista))

min 9.5
max 98.7
media 48.07333333333333
dev std 27.19971731879253


In [51]:
lista = lista * 1.10
lista

array([ 13.53,  25.74,  37.95,  50.16,  62.37,  74.58,  86.79, 108.57,
        96.36,  71.94,  59.73,  47.63,  35.31,  12.1 ,  10.45])

In [53]:
np.savetxt("numeri_mod.txt", lista, fmt="%0.2f")

In [57]:
np.save("lista.dat", lista)
dati = np.load("lista.dat.npy")
dati

array([ 13.53,  25.74,  37.95,  50.16,  62.37,  74.58,  86.79, 108.57,
        96.36,  71.94,  59.73,  47.63,  35.31,  12.1 ,  10.45])