# Numpy

In [1]:
# %pip install numpy
import numpy as np

In [2]:
v1 = np.array([1,2,3,4,5,6,7,8,9])
print(v1)

[1 2 3 4 5 6 7 8 9]


In [3]:
v1.shape

(9,)

In [6]:
v1.shape = (3,3)
print(v1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
v2 = np.array([1,2,3,4,5])
print(v2)
v2[2] = 9
print(v2)
print(v2[0])

[1 2 3 4 5]
[1 2 9 4 5]
1


In [9]:
v1[0,0] = 0
print(v1)

[[0 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
#estraggo una riga dalla matrice
print(v1[1])

[4 5 6]


In [12]:
#estraggo una colonna
print(v1[:,1])

[2 5 8]


modifiche agli array

In [13]:
n = np.array([1,2,3,4,5,6,7,8,9,10])
n2 = np.append(n, 100)
print(n2)

[  1   2   3   4   5   6   7   8   9  10 100]


In [14]:
n3 = np.insert(n, 3, 99)
print(n3)

[ 1  2  3 99  4  5  6  7  8  9 10]


In [15]:
print(n.dtype)

int32


In [17]:
n4 = np.append(n, 12.3)
print(n4)
print(n4.dtype)

[ 1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  12.3]
float64


In [20]:
#cambio il tipo di dati dell'array
n4 = n4.astype(np.int16)
print(n4)

[ 1  2  3  4  5  6  7  8  9 10 12]


operazioni con array

In [22]:
a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5])

print(a+b)
print(a-b)
print(a*b)

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]


In [23]:
print(a*1.10)

[11. 22. 33. 44. 55.]


In [24]:
print(a > 25)

[False False  True  True  True]


Generare numeri

In [26]:
#generare una sequenza
m = np.arange(1, 49)
print(m)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [27]:
m2 = np.arange(1,49).reshape(6,8)
print(m2)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]]


In [29]:
m = np.random.random( (4,4) )
print(m)
m2 = m * 100
print(m2)

[[0.07717316 0.3790383  0.71935661 0.91041425]
 [0.37808617 0.62259375 0.52835819 0.48878967]
 [0.96089584 0.83050909 0.78654079 0.61865621]
 [0.39298065 0.49061825 0.72623712 0.36797741]]
[[ 7.71731567 37.90382999 71.93566075 91.04142507]
 [37.80861689 62.25937488 52.83581876 48.87896683]
 [96.0895837  83.05090937 78.65407925 61.86562132]
 [39.29806452 49.06182477 72.62371159 36.79774105]]


In [30]:
m = np.random.randint(0, 100, (4,4))
print(m)

[[48 93 39 67]
 [80 84 59 47]
 [18 17 48 24]
 [12 27 58 24]]
