# Numpy

In [2]:
# %pip install numpy
import numpy as np

In [3]:
v1 = np.array([1,2,3,4,5,6,7,8,9])
print(v1)

[1 2 3 4 5 6 7 8 9]


In [4]:
v1.shape

(9,)

In [5]:
v1.shape = (3,3)
print(v1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
v2 = np.array([1,2,3,4,5])
print(v2)
v2[2] = 9
print(v2)
print(v2[0])

[1 2 3 4 5]
[1 2 9 4 5]
1


In [7]:
v1[0,0] = 0
print(v1)

[[0 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
#estraggo una riga dalla matrice
print(v1[1])

[4 5 6]


In [9]:
#estraggo una colonna
print(v1[:,1])

[2 5 8]


modifiche agli array

In [10]:
n = np.array([1,2,3,4,5,6,7,8,9,10])
n2 = np.append(n, 100)
print(n2)

[  1   2   3   4   5   6   7   8   9  10 100]


In [11]:
n3 = np.insert(n, 3, 99)
print(n3)

[ 1  2  3 99  4  5  6  7  8  9 10]


In [12]:
print(n.dtype)

int32


In [13]:
n4 = np.append(n, 12.3)
print(n4)
print(n4.dtype)

[ 1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  12.3]
float64


In [14]:
#cambio il tipo di dati dell'array
n4 = n4.astype(np.int16)
print(n4)

[ 1  2  3  4  5  6  7  8  9 10 12]


operazioni con array

In [15]:
a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5])

print(a+b)
print(a-b)
print(a*b)

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]


In [16]:
print(a*1.10)

[11. 22. 33. 44. 55.]


In [17]:
print(a > 25)

[False False  True  True  True]


Generare numeri

In [18]:
#generare una sequenza
m = np.arange(1, 49)
print(m)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [19]:
m2 = np.arange(1,49).reshape(6,8)
print(m2)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]]


In [20]:
m = np.random.random( (4,4) )
print(m)
m2 = m * 100
print(m2)

[[0.57809639 0.81329329 0.26728704 0.72640834]
 [0.20604314 0.17550627 0.70413693 0.89816619]
 [0.77092047 0.66078184 0.00594417 0.20217471]
 [0.91059656 0.84881576 0.49986007 0.4664485 ]]
[[57.8096393  81.32932932 26.72870374 72.64083413]
 [20.60431375 17.55062677 70.41369269 89.81661895]
 [77.09204691 66.07818383  0.59441679 20.21747107]
 [91.05965597 84.8815756  49.98600748 46.64484973]]


In [21]:
m = np.random.randint(0, 100, (4,4))
print(m)

[[81  3 51 40]
 [90 15 97 61]
 [61 91 60 66]
 [65 59 34 33]]


## Filtraggi

In [ ]:
n1 = np.random.randint(0, 100, 20) #20 numeri a caso tra 0 e 100
print(n1)

nf = n1[ n1<50 ]
print(nf)

[ 5 41 63 13 49 44 83 15 90 52 83 95 21 28 79 53 48 21 80 38]
[ 5 41 13 49 44 15 21 28 48 21 38]


In [25]:
#numeri uguali a 44
n2 = n1[ n1 == 44 ]
print(n2)

[44]


In [27]:
#solo i numeri pari
n3 = n1[ (n1%2) == 0 ]
print(n3) 

[44 90 52 28 48 80 38]


In [ ]:
#numeri in un intervallo
n4 = n1[ (n1 > 20) & (n1 < 40)  ] # & = AND, | = OR
print(n4)

[21 28 21 38]


## where

In [31]:
n5 = np.where( n1>50, n1, 0 )
print(n5)

[ 0  0 63  0  0  0 83  0 90 52 83 95  0  0 79 53  0  0 80  0]


In [32]:
n6 = np.where( (n1%2 == 0), 'p', 'd' )
print(n6)

['d' 'd' 'd' 'd' 'd' 'p' 'd' 'd' 'p' 'p' 'd' 'd' 'd' 'p' 'd' 'd' 'p' 'd'
 'p' 'p']
